name: devops workflow

on:
  push:
    branches: [ main ]

jobs:
  security-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v6
      with:
        fetch-depth: 0

    - name: SonarQube Scan
      uses: SonarSource/sonarqube-scan-action@v8.0.0
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ vars.SONAR_URL }}

    - name: Checkov scan
      uses: bridgecrewio/checkov-action@v12.1347.0
      with:
        directory: .
        soft_fail: true

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ vars.DOCKERHUB_USERNAME }}" --password-stdin

    - name: Build API image
      run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/simple-app-api:${{ github.sha }} -f s9/app01/api.Dockerfile s9/app01

    - name: Build frontend image
      run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/simple-app-frontend:${{ github.sha }} -f s9/app01/frontend.Dockerfile s9/app01

    - name: Build database image
      run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/simple-app-db:${{ github.sha }} -f s9/app01/db.Dockerfile s9/app01

    - name: Push API image
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/simple-app-api:${{ github.sha }}

    - name: Push frontend image
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/simple-app-frontend:${{ github.sha }}

    - name: Push database image
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/simple-app-db:${{ github.sha }}
    - name: test
      run: sudo docker images
